apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stress-ng
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stress-ng
    spec:
      containers:
      - image: alexeiled/stress-ng
        name: stress-ng
        command: ["/stress-ng"]
        args: ["-c", "200", "-l", "100", "-v"]
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m

# -c 2 : Spawn two workers
# -l 100  , -l P, --cpu-load P         load CPU by P %%, 0=sleep, 100=full load
# -v --verbose
